version: "3.8"
services:
  bridgehead-forward-proxy:
    image: samply/bridgehead-forward-proxy:develop
    environment:
      http_proxy: ${http_proxy}
    ports:
      - "3128:3128"
    volumes:
      - "./custom-certs:/docker/custom-certs:ro"
    tmpfs:
      - /var/log/squid
      - /var/spool/squid
